# Generated by Django 3.2.18 on 2023-04-11 06:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='initial_impact',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Front'), ('2', 'Right'), ('3', 'Back'), ('5', 'Left')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
