# Generated by Django 3.2.18 on 2023-08-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damaged_parts_svg_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damaged_parts_car', to='files.file'),
        ),
        migrations.AddField(
            model_name='car',
            name='initial_impact_svg_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_impact_car', to='files.file'),
        ),
    ]
