# Generated by Django 3.2.18 on 2023-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='participants_count',
            field=models.IntegerField(default=2),
        ),
    ]
