# Generated by Django 3.2.18 on 2023-08-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230830_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='crash_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
