# Generated by Django 3.2.18 on 2023-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_name_car_make_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_country',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
