# Generated by Django 3.2.18 on 2023-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20230428_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
