# Generated by Django 3.2.18 on 2024-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20231120_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tos_compliance',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
