# Generated by Django 3.2.18 on 2023-04-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0002_crash_revision'),
        ('cars', '0004_car_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='crash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='crashes.crash'),
        ),
    ]
