# Generated by Django 3.2.18 on 2023-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_crash_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='responsibility_type',
            field=models.CharField(blank=True, choices=[('ME', 'me'), ('ANOTHER', 'another'), ('UNKNOWN', 'unknown')], default=None, max_length=100),
        ),
    ]
