# Generated by Django 3.2.18 on 2023-09-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_responsibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='responsibility_type',
            field=models.CharField(blank=True, choices=[('ME', 'me'), ('ANOTHER', 'another'), ('UNKNOWN', 'unknown')], default=None, max_length=100, null=True),
        ),
    ]
