# Generated by Django 3.2.18 on 2023-09-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
                ('data', models.JSONField()),
                ('creator', models.CharField(blank=True, max_length=128)),
                ('crash_confirmed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.car')),
                ('crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='crashes.crash')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
