# Generated by Django 3.2.18 on 2023-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
