# Generated by Django 3.2.18 on 2023-07-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questions',
            new_name='sections',
        ),
    ]
