# Generated by Django 3.2.18 on 2023-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_rename_questions_questionnaire_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='creator',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
