# Generated by Django 3.2.18 on 2023-07-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0002_remove_crash_state'),
        ('questionnaires', '0003_questionnaire_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='crash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='crashes.crash'),
            preserve_default=False,
        ),
    ]
