# Generated by Django 3.2.18 on 2023-07-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_questionnaire_crash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='sections',
            new_name='data',
        ),
    ]
