# Generated by Django 3.2.18 on 2023-09-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_holders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyholder',
            old_name='email',
            new_name='email_phone_number',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='post_number',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='surname',
        ),
    ]
