# Generated by Django 3.2.18 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_holders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholder',
            name='country_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
