# Generated by Django 3.2.18 on 2023-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_holders', '0002_alter_policyholder_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='post_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='surname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
