# Generated by Django 3.2.18 on 2023-05-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_policy_holder'),
        ('policy_holders', '0003_auto_20230510_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyholder',
            name='id',
        ),
        migrations.AddField(
            model_name='policyholder',
            name='policy_holder',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.car'),
            preserve_default=False,
        ),
    ]
