# Generated by Django 3.2.18 on 2023-05-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_policy_holder'),
        ('policy_holders', '0006_auto_20230510_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyholder',
            name='id',
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy_holder', serialize=False, to='cars.car'),
        ),
    ]
