# Generated by Django 3.2.18 on 2023-08-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crashes', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
                ('confirmed_editors', models.CharField(max_length=256)),
                ('crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='crashes.crash')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
