# Generated by Django 3.2.18 on 2023-06-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('E', 'Empty'), ('P', 'Partial'), ('V', 'Validated')], default='E', max_length=1)),
                ('creator', models.CharField(blank=True, max_length=128)),
                ('crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketch', to='crashes.crash')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SketchCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.FloatField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketches.latlng')),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketch_cars', to='sketches.sketch')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='sketches.sketch')),
            ],
        ),
        migrations.AddField(
            model_name='latlng',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latlngs', to='sketches.polygon'),
        ),
    ]
