# Generated by Django 3.2.18 on 2023-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchcar',
            name='position',
        ),
        migrations.AddField(
            model_name='sketchcar',
            name='position_lat',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sketchcar',
            name='position_lng',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
