# Generated by Django 3.2.18 on 2023-08-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='confirmed_editors',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='files.file'),
        ),
    ]
