# Generated by Django 3.2.18 on 2023-06-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
        ('sketches', '0002_auto_20230626_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sketchcar',
            old_name='position_lat',
            new_name='position_east',
        ),
        migrations.RenameField(
            model_name='sketchcar',
            old_name='position_lng',
            new_name='position_north',
        ),
        migrations.AddField(
            model_name='sketchcar',
            name='position_south',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sketchcar',
            name='position_west',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sketch',
            name='crash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='crashes.crash'),
        ),
    ]
