# Generated by Django 3.2.18 on 2023-08-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
        ('sketches', '0003_auto_20230829_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='crash',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sketch', to='crashes.crash'),
        ),
    ]
