# Generated by Django 3.2.18 on 2023-08-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0005_alter_sketch_crash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sketch',
            old_name='file_id',
            new_name='file',
        ),
    ]
