# Generated by Django 3.2.18 on 2023-09-20 13:02

import api.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=api.files.models.OverwriteStorage(), upload_to=api.files.models.file_generate_upload_path)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.CharField(max_length=256)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
