# Generated by Django 3.2.18 on 2023-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
