# Generated by Django 3.2.18 on 2023-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20230907_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file_name',
        ),
    ]
