# Generated by Django 3.2.18 on 2023-09-20 09:57

import api.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_name_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=api.files.models.OverwriteStorage(), upload_to=api.files.models.file_generate_upload_path),
        ),
    ]
