# Generated by Django 3.2.18 on 2023-05-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_rename_name_car_make_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('revision', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256, null=True)),
                ('surname', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('driving_licence_number', models.CharField(max_length=256, null=True)),
                ('driving_licence_valid_from', models.DateTimeField(null=True)),
                ('driving_licence_valid_to', models.DateTimeField(null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='drivers', serialize=False, to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
