# Generated by Django 3.2.18 on 2023-08-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('revision', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256, null=True)),
                ('surname', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('driving_licence_number', models.CharField(max_length=256, null=True)),
                ('driving_licence_valid_from', models.DateTimeField(null=True)),
                ('driving_licence_valid_to', models.DateTimeField(null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
