# Generated by Django 3.2.18 on 2023-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
