# Generated by Django 3.2.18 on 2023-10-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_driving_licence_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='birthday',
            new_name='date_of_birth',
        ),
    ]
