# Generated by Django 3.2.18 on 2023-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
