# Generated by Django 3.2.18 on 2023-07-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20230629_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
    ]
