# Generated by Django 3.2.18 on 2023-09-20 13:02

import api.crashes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default=api.crashes.models.generate_unique_code, max_length=8, null=True, unique=True)),
                ('closed', models.BooleanField(default=False)),
                ('participants', models.IntegerField(default=2)),
                ('creator', models.CharField(blank=True, max_length=128)),
                ('date_of_accident', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('place', models.CharField(max_length=256, null=True)),
                ('injuries', models.BooleanField(null=True)),
                ('vehicle_material_damage', models.BooleanField(null=True)),
                ('other_material_damage', models.BooleanField(null=True)),
                ('witnesses', models.TextField(blank=True)),
                ('additional_crash_data', models.TextField(blank=True)),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crash_pdf', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
