# Generated by Django 3.2.18 on 2023-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crash',
            old_name='locality',
            new_name='country',
        ),
        migrations.AddField(
            model_name='crash',
            name='place',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
