# Generated by Django 3.2.18 on 2023-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='creator',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
