# Generated by Django 3.2.18 on 2023-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='additional_crash_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crash',
            name='witnesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
