# Generated by Django 3.2.18 on 2023-08-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crash_pdf', to='files.file'),
        ),
    ]
