# Generated by Django 3.2.18 on 2023-08-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
        ('crashes', '0002_crash_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crash_pdf', to='files.file'),
        ),
    ]
