# Generated by Django 3.2.18 on 2023-11-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0002_auto_20230926_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='timezone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
