# Generated by Django 3.2.18 on 2023-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0003_alter_crash_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='additional_crash_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crash',
            name='witnesses',
            field=models.TextField(blank=True),
        ),
    ]
