# Generated by Django 3.2.18 on 2023-06-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circumstance',
            fields=[
                ('revision', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('E', 'Empty'), ('P', 'Partial'), ('V', 'Validated')], default='E', max_length=1)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='circumstances', serialize=False, to='cars.car')),
                ('parked_stopped', models.BooleanField(default=False)),
                ('leaving_parking_opening_door', models.BooleanField(default=False)),
                ('entering_parking', models.BooleanField(default=False)),
                ('emerging_from_car_park', models.BooleanField(default=False)),
                ('entering_car_park', models.BooleanField(default=False)),
                ('entering_roundabout', models.BooleanField(default=False)),
                ('circulating_roundabout', models.BooleanField(default=False)),
                ('rear_same_direction', models.BooleanField(default=False)),
                ('same_direction_different_lane', models.BooleanField(default=False)),
                ('changing_lanes', models.BooleanField(default=False)),
                ('overtaking', models.BooleanField(default=False)),
                ('turning_right', models.BooleanField(default=False)),
                ('turning_left', models.BooleanField(default=False)),
                ('reversing', models.BooleanField(default=False)),
                ('driving_on_opposite_lane', models.BooleanField(default=False)),
                ('from_right_crossing', models.BooleanField(default=False)),
                ('disregarding_right_of_way_red_light', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
