# Generated by Django 3.2.18 on 2023-07-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circumstances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circumstance',
            name='state',
        ),
    ]
