from api.common.pdf_generator.statement_enum import AccidentStatementEnums

class FieldType:
    String = 'STRING',
    Radio = 'RADIO',
    Checkbox = 'CHECKBOX'


field_mapper = {
    ' Datum nesrece': {'name': AccidentStatementEnums.DATE_OF_ACCIDENT, 'type': FieldType.String},
    ' Ura': {'name': AccidentStatementEnums.TIME_OF_ACCIDENT, 'type': FieldType.String},
    ' Drzava': {'name': AccidentStatementEnums.ACCIDENT_COUNTRY, 'type': FieldType.String},
    ' Kraj 1': {'name': AccidentStatementEnums.ACCIDENT_PLACE_1, 'type': FieldType.String, 'font_size': 6},
    ' Kraj 2': {'name': AccidentStatementEnums.ACCIDENT_PLACE_2, 'type': FieldType.String, 'font_size': 6},
    ' ponesrecenci NE': {'name': AccidentStatementEnums.INJURIES_NO, 'type': FieldType.Checkbox},
    ' ponesrecenci DA': {'name': AccidentStatementEnums.INJURIES_YES, 'type': FieldType.Checkbox},
    ' Skoda NE': {'name': AccidentStatementEnums.VEHICLE_MATERIAL_DAMAGE_NO, 'type': FieldType.Checkbox},
    ' Skoda DA': {'name': AccidentStatementEnums.VEHICLE_MATERIAL_DAMAGE_YES, 'type': FieldType.Checkbox},
    ' Skoda 2 NE': {'name': AccidentStatementEnums.OTHER_MATERIAL_DAMAGE_NO, 'type': FieldType.Checkbox},
    ' Skoda 2 DA': {'name': AccidentStatementEnums.OTHER_MATERIAL_DAMAGE_YES, 'type': FieldType.Checkbox},
    ' Price': {'name': AccidentStatementEnums.WITNESSES, 'type': FieldType.String},
    'A Priimek vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_SURNAME}_1', 'type': FieldType.String},
    'A Ime vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_NAME}_1', 'type': FieldType.String},
    'A Naslov vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_ADDRESS}_1', 'type': FieldType.String},
    'A Postna stevilka vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_POST_NUMBER}_1', 'type': FieldType.String},
    'A Drzava vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_COUNTRY}_1', 'type': FieldType.String},
    'A Telefon-Email vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_EMAIL}_1', 'type': FieldType.String},
    'A Znamka vozilo': {'name': f'{AccidentStatementEnums.CAR_TYPE}_1', 'type': FieldType.String},
    'A Registrska vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_PLATE}_1', 'type': FieldType.String},
    'A Drzava registracije vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_COUNTRY}_1', 'type': FieldType.String},
    'A Registrska prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER}_1', 'type': FieldType.String},
    'A Drzava registracije prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER_COUNTRY}_1', 'type': FieldType.String},
    'A Zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_NAME}_1', 'type': FieldType.String},
    'A st police vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_POLICY_NUMBER}_1', 'type': FieldType.String},
    'A st karte vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_GREEN_CARD}_1', 'type': FieldType.String},
    'A veljavnost OD vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_FROM}_1', 'type': FieldType.String, 'font_size': 6},
    'A veljavnost DO vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_UNTIL}_1', 'type': FieldType.String, 'font_size': 6},
    'A poslovno mesto vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY}_1', 'type': FieldType.String},
    'A Agencija vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_1', 'type': FieldType.String},
    'A Telefon-Email zav vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_EMAIL}_1', 'type': FieldType.String},
    'A Naslov zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_1', 'type': FieldType.String},
    'A Drzava zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_COUNTRY}_1', 'type': FieldType.String},
    'A Priimek voznik': {'name': f'{AccidentStatementEnums.DRIVER_SURNAME}_1', 'type': FieldType.String},
    'A Ime voznik': {'name': f'{AccidentStatementEnums.DRIVER_NAME}_1', 'type': FieldType.String},
    'A rojstvo voznik': {'name': f'{AccidentStatementEnums.DRIVER_BIRTHDAY}_1', 'type': FieldType.String},
    'A Naslov voznik': {'name': f'{AccidentStatementEnums.DRIVER_ADDRESS}_1', 'type': FieldType.String},
    'A Telefon-Email voznik': {'name': f'{AccidentStatementEnums.DRIVER_EMAIL}_1', 'type': FieldType.String},
    'A Drzava voznik': {'name': f'{AccidentStatementEnums.DRIVER_COUNTRY}_1', 'type': FieldType.String},
    'A Voznisko voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_NUMBER}_1', 'type': FieldType.String},
    'A Kategorija voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_CATEGORY}_1', 'type': FieldType.String},
    'A Veljavnost voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_VALID_TO}_1', 'type': FieldType.String},
    'A Kasko NE': {'name': f'{AccidentStatementEnums.CAR_CASCO_NO}_1', 'type': FieldType.Checkbox},
    'A Kasko DA': {'name': f'{AccidentStatementEnums.CAR_CASCO_YES}_1', 'type': FieldType.Checkbox},
    'A Pripombe Vozilo': {'name': f'{AccidentStatementEnums.ADDITIONAL_DATA}_1', 'type': FieldType.String},

    # CAR 2

    'B Priimek vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_SURNAME}_2', 'type': FieldType.String},
    'B Ime vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_NAME}_2', 'type': FieldType.String},
    'B Naslov vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_ADDRESS}_2', 'type': FieldType.String},
    'B Postna stevilka vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_POST_NUMBER}_2', 'type': FieldType.String},
    'B Drzava vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_COUNTRY}_2', 'type': FieldType.String},
    'B Telefon-Email vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_EMAIL}_2', 'type': FieldType.String},
    'B Znamka vozilo': {'name': f'{AccidentStatementEnums.CAR_TYPE}_2', 'type': FieldType.String},
    'B Registrska vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_PLATE}_2', 'type': FieldType.String},
    'B Drzava registracije vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_COUNTRY}_2', 'type': FieldType.String},
    'B Registrska prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER}_2', 'type': FieldType.String},
    'B Drzava registracije prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER_COUNTRY}_2', 'type': FieldType.String},
    'B Zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_NAME}_2', 'type': FieldType.String},
    'B st police vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_POLICY_NUMBER}_2', 'type': FieldType.String},
    'B st karte vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_GREEN_CARD}_2', 'type': FieldType.String},
    'B veljavnost OD vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_UNTIL}_2', 'type': FieldType.String, 'font_size': 6},
    'B veljavnost DO vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_FROM}_2', 'type': FieldType.String, 'font_size': 6},
    'B poslovno mesto vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY}_2', 'type': FieldType.String},
    'B Telefon-Email zav vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_EMAIL}_2', 'type': FieldType.String},
    'B Agencija vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_2', 'type': FieldType.String},
    'B Naslov zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_2', 'type': FieldType.String},
    'B Drzava zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_COUNTRY}_2', 'type': FieldType.String},
    'B Priimek voznik': {'name': f'{AccidentStatementEnums.DRIVER_SURNAME}_2', 'type': FieldType.String},
    'B Ime voznik': {'name': f'{AccidentStatementEnums.DRIVER_NAME}_2', 'type': FieldType.String},
    'B rojstvo voznik': {'name': f'{AccidentStatementEnums.DRIVER_BIRTHDAY}_2', 'type': FieldType.String},
    'B Naslov voznik': {'name': f'{AccidentStatementEnums.DRIVER_ADDRESS}_2', 'type': FieldType.String},
    'B Telefon-Email voznik': {'name': f'{AccidentStatementEnums.DRIVER_EMAIL}_2', 'type': FieldType.String},
    'B Drzava voznik': {'name': f'{AccidentStatementEnums.DRIVER_COUNTRY}_2', 'type': FieldType.String},
    'B Voznisko voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_NUMBER}_2', 'type': FieldType.String},
    'B Kategorija voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_CATEGORY}_2', 'type': FieldType.String},
    'B Veljavnost voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_VALID_TO}_2', 'type': FieldType.String},
    'B Kasko NE': {'name': f'{AccidentStatementEnums.CAR_CASCO_NO}_2', 'type': FieldType.Checkbox},
    'B Kasko DA': {'name': f'{AccidentStatementEnums.CAR_CASCO_YES}_2', 'type': FieldType.Checkbox},
    'B Pripombe Vozilo': {'name': f'{AccidentStatementEnums.ADDITIONAL_DATA}_2', 'type': FieldType.String},

    'A Check Box - 1': {'name': f'{AccidentStatementEnums.PARKED_STOPPED}_1', 'type': FieldType.Checkbox},
    'A Check Box - 2': {'name': f'{AccidentStatementEnums.LEAVING_PARKING_OPENING_DOOR}_1', 'type': FieldType.Checkbox},
    'A Check Box - 3': {'name': f'{AccidentStatementEnums.ENTERING_PARKING}_1', 'type': FieldType.Checkbox},
    'A Check Box - 4': {'name': f'{AccidentStatementEnums.EMERGING_FROM_CAR_PARK}_1', 'type': FieldType.Checkbox},
    'A Check Box - 5': {'name': f'{AccidentStatementEnums.ENTERING_CAR_PARK}_1', 'type': FieldType.Checkbox},
    'A Check Box - 6': {'name': f'{AccidentStatementEnums.ENTERING_ROUNDABOUT}_1', 'type': FieldType.Checkbox},
    'A Check Box - 7': {'name': f'{AccidentStatementEnums.CIRCULATING_ROUNDABOUT}_1', 'type': FieldType.Checkbox},
    'A Check Box - 8': {'name': f'{AccidentStatementEnums.REAR_SAME_DIRECTION}_1', 'type': FieldType.Checkbox},
    'A Check Box - 9': {'name': f'{AccidentStatementEnums.SAME_DIRECTION_DIFFERENT_LANE}_1', 'type': FieldType.Checkbox},
    'A Check Box - 10': {'name': f'{AccidentStatementEnums.CHANGING_LANES}_1', 'type': FieldType.Checkbox},
    'A Check Box - 11': {'name': f'{AccidentStatementEnums.OVERTAKING}_1', 'type': FieldType.Checkbox},
    'A Check Box - 12': {'name': f'{AccidentStatementEnums.TURNING_RIGHT}_1', 'type': FieldType.Checkbox},
    'A Check Box - 13': {'name': f'{AccidentStatementEnums.TURNING_LEFT}_1', 'type': FieldType.Checkbox},
    'A Check Box - 14': {'name': f'{AccidentStatementEnums.REVERSING}_1', 'type': FieldType.Checkbox},
    'A Check Box - 15': {'name': f'{AccidentStatementEnums.DRIVING_ON_OPPOSITE_LANE}_1', 'type': FieldType.Checkbox},
    'A Check Box - 16': {'name': f'{AccidentStatementEnums.FROM_RIGHT_CROSSING}_1', 'type': FieldType.Checkbox},
    'A Check Box - 17': {'name': f'{AccidentStatementEnums.DISREGARDING_RIGHT_OF_WAY_RED_LIGHT}_1', 'type': FieldType.Checkbox},
    'A Okenca': {'name': f'{AccidentStatementEnums.CIRCUMSTANCES_COUNT}_1', 'type': FieldType.String},
    'A Podpis': {'name': f'{AccidentStatementEnums.SIGNATURE}_1', 'type': FieldType.String},

    'B Check Box - 1': {'name': f'{AccidentStatementEnums.PARKED_STOPPED}_2', 'type': FieldType.Checkbox},
    'B Check Box - 2': {'name': f'{AccidentStatementEnums.LEAVING_PARKING_OPENING_DOOR}_2', 'type': FieldType.Checkbox},
    'B Check Box - 3': {'name': f'{AccidentStatementEnums.ENTERING_PARKING}_2', 'type': FieldType.Checkbox},
    'B Check Box - 4': {'name': f'{AccidentStatementEnums.EMERGING_FROM_CAR_PARK}_2', 'type': FieldType.Checkbox},
    'B Check Box - 5': {'name': f'{AccidentStatementEnums.ENTERING_CAR_PARK}_2', 'type': FieldType.Checkbox},
    'B Check Box - 6': {'name': f'{AccidentStatementEnums.ENTERING_ROUNDABOUT}_2', 'type': FieldType.Checkbox},
    'B Check Box - 7': {'name': f'{AccidentStatementEnums.CIRCULATING_ROUNDABOUT}_2', 'type': FieldType.Checkbox},
    'B Check Box - 8': {'name': f'{AccidentStatementEnums.REAR_SAME_DIRECTION}_2', 'type': FieldType.Checkbox},
    'B Check Box - 9': {'name': f'{AccidentStatementEnums.SAME_DIRECTION_DIFFERENT_LANE}_2','type': FieldType.Checkbox},
    'B Check Box - 10': {'name': f'{AccidentStatementEnums.CHANGING_LANES}_2', 'type': FieldType.Checkbox},
    'B Check Box - 11': {'name': f'{AccidentStatementEnums.OVERTAKING}_2', 'type': FieldType.Checkbox},
    'B Check Box - 12': {'name': f'{AccidentStatementEnums.TURNING_RIGHT}_2', 'type': FieldType.Checkbox},
    'B Check Box - 13': {'name': f'{AccidentStatementEnums.TURNING_LEFT}_2', 'type': FieldType.Checkbox},
    'B Check Box - 14': {'name': f'{AccidentStatementEnums.REVERSING}_2', 'type': FieldType.Checkbox},
    'B Check Box - 15': {'name': f'{AccidentStatementEnums.DRIVING_ON_OPPOSITE_LANE}_2', 'type': FieldType.Checkbox},
    'B Check Box - 16': {'name': f'{AccidentStatementEnums.FROM_RIGHT_CROSSING}_2', 'type': FieldType.Checkbox},
    'B Check Box - 17': {'name': f'{AccidentStatementEnums.DISREGARDING_RIGHT_OF_WAY_RED_LIGHT}_2','type': FieldType.Checkbox},
    'B Okenca': {'name': f'{AccidentStatementEnums.CIRCUMSTANCES_COUNT}_2', 'type': FieldType.String},
    'B Podpis': {'name': f'{AccidentStatementEnums.SIGNATURE}_2', 'type': FieldType.String},
}
