from api.common.pdf_generator.statement_enum import AccidentStatementEnums

class FieldType:
    String = 'STRING',
    Radio = 'RADIO',
    Checkbox = 'CHECKBOX',
    TextArea = 'TEXTAREA',


field_mapper = {
    '1. Datum nesrece': {'name': AccidentStatementEnums.DATE_OF_ACCIDENT, 'type': FieldType.String},
    '1. Ura': {'name': AccidentStatementEnums.TIME_OF_ACCIDENT, 'type': FieldType.String},
    '2. Drzava': {'name': AccidentStatementEnums.ACCIDENT_COUNTRY, 'type': FieldType.String},
    '2. Kraj 1': {'name': AccidentStatementEnums.ACCIDENT_PLACE_1, 'type': FieldType.String},
    '2. Kraj 2': {'name': AccidentStatementEnums.ACCIDENT_PLACE_2, 'type': FieldType.String},
    '3. ponesrecenci NE': {'name': AccidentStatementEnums.INJURIES_NO, 'type': FieldType.Checkbox},
    '3. ponesrecenci DA': {'name': AccidentStatementEnums.INJURIES_YES, 'type': FieldType.Checkbox},
    '4. Skoda NE': {'name': AccidentStatementEnums.VEHICLE_MATERIAL_DAMAGE_NO, 'type': FieldType.Checkbox},
    '4. Skoda DA': {'name': AccidentStatementEnums.VEHICLE_MATERIAL_DAMAGE_YES, 'type': FieldType.Checkbox},
    '4. Skoda 2 NE': {'name': AccidentStatementEnums.OTHER_MATERIAL_DAMAGE_NO, 'type': FieldType.Checkbox},
    '4. Skoda 2 DA': {'name': AccidentStatementEnums.OTHER_MATERIAL_DAMAGE_YES, 'type': FieldType.Checkbox},
    '5. Price': {'name': AccidentStatementEnums.WITNESSES, 'type': FieldType.TextArea},
    '6.A Priimek vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_SURNAME}_1', 'type': FieldType.String},
    '6.A Ime vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_NAME}_1', 'type': FieldType.String},
    '6.A Naslov vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_ADDRESS}_1', 'type': FieldType.String},
    '6.A Postna stevilka vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_POST_NUMBER}_1', 'type': FieldType.String},
    '6.A Drzava vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_COUNTRY}_1', 'type': FieldType.String},
    '6.A Telefon-Email vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_EMAIL}_1', 'type': FieldType.String},
    '7.A Znamka vozilo': {'name': f'{AccidentStatementEnums.CAR_TYPE}_1', 'type': FieldType.String},
    '7.A Registrska vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_PLATE}_1', 'type': FieldType.String},
    '7.A Drzava registracije vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_COUNTRY}_1', 'type': FieldType.String},
    '7.A Registrska prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER}_1', 'type': FieldType.String},
    '7.A Drzava registracije prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER_COUNTRY}_1', 'type': FieldType.String},
    '8.A Zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_NAME}_1', 'type': FieldType.String},
    '8.A st police vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_POLICY_NUMBER}_1', 'type': FieldType.String},
    '8.A st karte vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_GREEN_CARD}_1', 'type': FieldType.String},
    '8.A veljavnost OD vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_FROM}_1', 'type': FieldType.String},
    '8.A veljavnost DO vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_UNTIL}_1', 'type': FieldType.String},
    '8.A poslovno mesto vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY}_1', 'type': FieldType.String},
    '8.A Agencija vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_1', 'type': FieldType.String},
    '8.A Telefon-Email zav vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_EMAIL}_1', 'type': FieldType.String},
    '8.A Naslov zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_1', 'type': FieldType.String},
    '8.A Drzava zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_COUNTRY}_1', 'type': FieldType.String},
    '9.A Priimek voznik': {'name': f'{AccidentStatementEnums.DRIVER_SURNAME}_1', 'type': FieldType.String},
    '9.A Ime voznik': {'name': f'{AccidentStatementEnums.DRIVER_NAME}_1', 'type': FieldType.String},
    '9.A rojstvo voznik': {'name': f'{AccidentStatementEnums.DRIVER_BIRTHDAY}_1', 'type': FieldType.String},
    '9.A Naslov voznik': {'name': f'{AccidentStatementEnums.DRIVER_ADDRESS}_1', 'type': FieldType.String},
    '9.A Telefon-Email voznik': {'name': f'{AccidentStatementEnums.DRIVER_EMAIL}_1', 'type': FieldType.String},
    '9.A Drzava voznik': {'name': f'{AccidentStatementEnums.DRIVER_COUNTRY}_1', 'type': FieldType.String},
    '9.A Voznisko voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_NUMBER}_1', 'type': FieldType.String},
    '9.A Kategorija voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_CATEGORY}_1', 'type': FieldType.String},
    '9.A Veljavnost voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_VALID_TO}_1', 'type': FieldType.String},
    '8.A Kasko NE': {'name': f'{AccidentStatementEnums.CAR_CASCO_NO}_1', 'type': FieldType.Checkbox},
    '8.A Kasko DA': {'name': f'{AccidentStatementEnums.CAR_CASCO_YES}_1', 'type': FieldType.Checkbox},
    '14.A Pripombe Vozilo': {'name': f'{AccidentStatementEnums.ADDITIONAL_DATA}_1', 'type': FieldType.TextArea},

    # CAR 2

    '6.B Priimek vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_SURNAME}_2', 'type': FieldType.String},
    '6.B Ime vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_NAME}_2', 'type': FieldType.String},
    '6.B Naslov vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_ADDRESS}_2', 'type': FieldType.String},
    '6.B Postna stevilka vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_POST_NUMBER}_2', 'type': FieldType.String},
    '6.B Drzava vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_COUNTRY}_2', 'type': FieldType.String},
    '6.B Telefon-Email vozilo': {'name': f'{AccidentStatementEnums.POLICY_HOLDER_EMAIL}_2', 'type': FieldType.String},
    '7.B Znamka vozilo': {'name': f'{AccidentStatementEnums.CAR_TYPE}_2', 'type': FieldType.String},
    '7.B Registrska vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_PLATE}_2', 'type': FieldType.String},
    '7.B Drzava registracije vozilo': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_COUNTRY}_2', 'type': FieldType.String},
    '7.B Registrska prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER}_2', 'type': FieldType.String},
    '7.B Drzava registracije prikolica': {'name': f'{AccidentStatementEnums.CAR_REGISTRATION_TRAILER_COUNTRY}_2', 'type': FieldType.String},
    '8.B Zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_NAME}_2', 'type': FieldType.String},
    '8.B st police vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_POLICY_NUMBER}_2', 'type': FieldType.String},
    '8.B st karte vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_GREEN_CARD}_2', 'type': FieldType.String},
    '8.B veljavnost OD vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_FROM}_2', 'type': FieldType.String},
    '8.B veljavnost DO vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_VALID_UNTIL}_2', 'type': FieldType.String},
    '8.B poslovno mesto vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY}_2', 'type': FieldType.String},
    '8.B Telefon-Email zav vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_EMAIL}_2', 'type': FieldType.String},
    '8.B Agencija vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_2', 'type': FieldType.String},
    '8.B Naslov zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_NAME}_2', 'type': FieldType.String},
    '8.B Drzava zavarovalnica vozilo': {'name': f'{AccidentStatementEnums.INSURANCE_AGENCY_COUNTRY}_2', 'type': FieldType.String},
    '9.B Priimek voznik': {'name': f'{AccidentStatementEnums.DRIVER_SURNAME}_2', 'type': FieldType.String},
    '9.B Ime voznik': {'name': f'{AccidentStatementEnums.DRIVER_NAME}_2', 'type': FieldType.String},
    '9.B rojstvo voznik': {'name': f'{AccidentStatementEnums.DRIVER_BIRTHDAY}_2', 'type': FieldType.String},
    '9.B Naslov voznik': {'name': f'{AccidentStatementEnums.DRIVER_ADDRESS}_2', 'type': FieldType.String},
    '9.B Telefon-Email voznik': {'name': f'{AccidentStatementEnums.DRIVER_EMAIL}_2', 'type': FieldType.String},
    '9.B Drzava voznik': {'name': f'{AccidentStatementEnums.DRIVER_COUNTRY}_2', 'type': FieldType.String},
    '9.B Voznisko voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_NUMBER}_2', 'type': FieldType.String},
    '9.B Kategorija voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_CATEGORY}_2', 'type': FieldType.String},
    '9.B Veljavnost voznik': {'name': f'{AccidentStatementEnums.DRIVER_LICENSE_VALID_TO}_2', 'type': FieldType.String},
    '8.B Kasko NE': {'name': f'{AccidentStatementEnums.CAR_CASCO_NO}_2', 'type': FieldType.Checkbox},
    '8.B Kasko DA': {'name': f'{AccidentStatementEnums.CAR_CASCO_YES}_2', 'type': FieldType.Checkbox},
    '14.B Pripombe Vozilo': {'name': f'{AccidentStatementEnums.ADDITIONAL_DATA}_2', 'type': FieldType.TextArea},

    '12.A Check Box - 1': {'name': f'{AccidentStatementEnums.PARKED_STOPPED}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 2': {'name': f'{AccidentStatementEnums.LEAVING_PARKING_OPENING_DOOR}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 3': {'name': f'{AccidentStatementEnums.ENTERING_PARKING}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 4': {'name': f'{AccidentStatementEnums.EMERGING_FROM_CAR_PARK}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 5': {'name': f'{AccidentStatementEnums.ENTERING_CAR_PARK}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 6': {'name': f'{AccidentStatementEnums.ENTERING_ROUNDABOUT}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 7': {'name': f'{AccidentStatementEnums.CIRCULATING_ROUNDABOUT}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 8': {'name': f'{AccidentStatementEnums.REAR_SAME_DIRECTION}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 9': {'name': f'{AccidentStatementEnums.SAME_DIRECTION_DIFFERENT_LANE}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 10': {'name': f'{AccidentStatementEnums.CHANGING_LANES}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 11': {'name': f'{AccidentStatementEnums.OVERTAKING}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 12': {'name': f'{AccidentStatementEnums.TURNING_RIGHT}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 13': {'name': f'{AccidentStatementEnums.TURNING_LEFT}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 14': {'name': f'{AccidentStatementEnums.REVERSING}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 15': {'name': f'{AccidentStatementEnums.DRIVING_ON_OPPOSITE_LANE}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 16': {'name': f'{AccidentStatementEnums.FROM_RIGHT_CROSSING}_1', 'type': FieldType.Checkbox},
    '12.A Check Box - 17': {'name': f'{AccidentStatementEnums.DISREGARDING_RIGHT_OF_WAY_RED_LIGHT}_1', 'type': FieldType.Checkbox},
    '12.A Okenca': {'name': f'{AccidentStatementEnums.CIRCUMSTANCES_COUNT}_1', 'type': FieldType.String},
    '15.A Podpis': {'name': f'{AccidentStatementEnums.SIGNATURE}_1', 'type': FieldType.TextArea, 'font_size': 5},

    '12.B Check Box - 1': {'name': f'{AccidentStatementEnums.PARKED_STOPPED}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 2': {'name': f'{AccidentStatementEnums.LEAVING_PARKING_OPENING_DOOR}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 3': {'name': f'{AccidentStatementEnums.ENTERING_PARKING}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 4': {'name': f'{AccidentStatementEnums.EMERGING_FROM_CAR_PARK}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 5': {'name': f'{AccidentStatementEnums.ENTERING_CAR_PARK}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 6': {'name': f'{AccidentStatementEnums.ENTERING_ROUNDABOUT}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 7': {'name': f'{AccidentStatementEnums.CIRCULATING_ROUNDABOUT}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 8': {'name': f'{AccidentStatementEnums.REAR_SAME_DIRECTION}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 9': {'name': f'{AccidentStatementEnums.SAME_DIRECTION_DIFFERENT_LANE}_2','type': FieldType.Checkbox},
    '12.B Check Box - 10': {'name': f'{AccidentStatementEnums.CHANGING_LANES}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 11': {'name': f'{AccidentStatementEnums.OVERTAKING}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 12': {'name': f'{AccidentStatementEnums.TURNING_RIGHT}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 13': {'name': f'{AccidentStatementEnums.TURNING_LEFT}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 14': {'name': f'{AccidentStatementEnums.REVERSING}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 15': {'name': f'{AccidentStatementEnums.DRIVING_ON_OPPOSITE_LANE}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 16': {'name': f'{AccidentStatementEnums.FROM_RIGHT_CROSSING}_2', 'type': FieldType.Checkbox},
    '12.B Check Box - 17': {'name': f'{AccidentStatementEnums.DISREGARDING_RIGHT_OF_WAY_RED_LIGHT}_2','type': FieldType.Checkbox},
    '12.B Okenca': {'name': f'{AccidentStatementEnums.CIRCUMSTANCES_COUNT}_2', 'type': FieldType.Checkbox},
    '15.B Podpis': {'name': f'{AccidentStatementEnums.SIGNATURE}_2', 'type': FieldType.TextArea, 'font_size': 5},
}
