# Generated by Django 3.2.18 on 2023-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
