# Generated by Django 3.2.18 on 2023-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_insurance_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='agent_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
