# Generated by Django 3.2.18 on 2023-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_insurance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='damage_insured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='green_card',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
